require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/constitution_articles", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ConstitutionArticle. As you add validations to ConstitutionArticle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      title: Faker::Lorem.word,
      content: Faker::Lorem.paragraph
    }
  }

  let(:invalid_attributes) {
    {
      fail: Faker::Lorem.word
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ConstitutionArticlesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      ConstitutionArticle.create! valid_attributes
      get api_v1_constitution_articles_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /active" do
    it "renders a successful response" do
      ConstitutionArticle.create! valid_attributes
      get active_api_v1_constitution_articles_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      constitution_article = ConstitutionArticle.create! valid_attributes
      get api_v1_constitution_article_url(constitution_article), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ConstitutionArticle" do
        expect {
          post api_v1_constitution_articles_url,
               params: { constitution_article: valid_attributes }, headers: valid_headers, as: :json
        }.to change(ConstitutionArticle, :count).by(1)
      end

      it "renders a JSON response with the new constitution_article" do
        post api_v1_constitution_articles_url,
             params: { constitution_article: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ConstitutionArticle" do
        expect {
          post api_v1_constitution_articles_url,
               params: { constitution_article: invalid_attributes }, as: :json
        }.to change(ConstitutionArticle, :count).by(0)
      end

      it "renders a JSON response with errors for the new constitution_article" do
        post api_v1_constitution_articles_url,
             params: { constitution_article: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested constitution_article" do
      constitution_article = ConstitutionArticle.create! valid_attributes
      expect {
        delete api_v1_constitution_article_url(constitution_article), headers: valid_headers, as: :json
      }.to change(ConstitutionArticle, :count).by(-1)
    end
  end
end
