require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api_v1/public/fields", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Field. As you add validations to Field, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {
    name: Faker::Lorem.word,
    google_maps_url: Faker::Internet.url
  } }

  let(:invalid_attributes) { {
    fail: Faker::Lorem.word
  } }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # FieldsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /active" do
    it "renders a successful response" do
      Field.create! valid_attributes
      get api_v1_public_fields_active_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

end
